# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: python:2.7

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - pip --version
          - tox --version
          - cp config.yml.sample config.yml
          - tox
