# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image:
  name: moreaghost/morea-ghost:2017.07.03
  username: moreaghost
  password: ***REMOVED***
  email: ghost-devops@morea.fr

pipelines:
  default:
    - step:
        script:
          - git --version
          - git status
          - pip install -r requirements.txt
          - pip --version
          - tox --version
          - cp config.yml.sample config.yml
          - tox
