# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image:
  name: moreaghost/morea-ghost:2017.11.30-5
  username: $DOCKER_HUB_LOGIN
  password: $DOCKER_HUB_PASSWORD
  email: ghost-devops@morea.fr

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - ./bitbucket-pipelines.sh

  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - ./bitbucket-pipelines.sh history

    dev:
      - step:
          caches:
            - pip
          script:
            - ./bitbucket-pipelines.sh history

    GHOST-547_enable_git-secret_scan:
      - step:
          caches:
            - pip
          script:
            - ./bitbucket-pipelines.sh history
