# docker-compose.yml
version: '2'

services:
  queue:
    image: redis
    ports:
     - '6379'
    networks:
      - dbs

  backend:
    image: mongo
    ports:
      - '27017'
    networks:
      - dbs

  worker:
    build:
      context: .
    image: ghost
    working_dir: /usr/local/share/ghost
    volumes:
      - .:/usr/local/share/ghost
      - log:/var/log/ghost
    networks:
      - dbs
    command: python run_rqworkers.py
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  api:
    build:
      context: .
    image: ghost
    working_dir: /usr/local/share/ghost
    volumes:
      - .:/usr/local/share/ghost
      - log:/var/log/ghost
    ports:
      - '5000:5000'
    networks:
      - dbs
      - front
    command: python run.py
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  web-ui:
    build:
      context: .
    image: ghost
    working_dir: /usr/local/share/ghost
    volumes:
      - .:/usr/local/share/ghost
      - log:/var/log/ghost
    ports:
      - '5001:5001'
    networks:
      - front
    command: python run_web_ui.py
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  nginx:
    image: nginx:latest
    volumes:
      - .:/usr/local/share/ghost
      - ./nginx-ghost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - front

networks:
  dbs:
    driver: bridge
  front:
    driver: bridge

volumes:
  log:
    driver: local
